import type {
  ChatConversation,
  ChatMessage,
  Coupon,
  DashboardMetrics,
  Expense,
  InventoryItem,
  LoyaltyHistory,
  Notification,
  Order,
  Poll,
  Post,
  Product,
  Profile,
  Review,
  Story,
} from '../types/domain';
import { huskyBrand } from '../config/huskyBrand';

const now = new Date().toISOString();
const day = 24 * 60 * 60 * 1000;

export const demoProfile: Profile = {
  id: 'demo-user',
  name: 'Cliente da Matilha',
  email: 'cliente@huskyclub.demo',
  phone: huskyBrand.whatsapp,
  avatar_url: null,
  birth_date: '1996-08-18',
  neighborhood: 'Centro',
  bio: 'Apaixonado por potinhos e brownies.',
  role: 'customer',
  points: 128,
  level: 'Husky Curioso',
  created_at: new Date(Date.now() - 100 * day).toISOString(),
  updated_at: now,
};

export const demoAdminProfile: Profile = {
  ...demoProfile,
  id: 'demo-admin',
  name: 'Admin Husky',
  email: 'admin@huskyclub.demo',
  role: 'admin',
  points: 0,
  level: 'Husky Supremo',
};

export const demoProducts: Product[] = [
  {
    id: 'prod-lambe',
    name: 'Lambe Lambe Brigadeiro',
    slug: 'lambe-lambe-brigadeiro',
    category: 'Bolos de pote',
    short_description: 'Bolo de chocolate com muito brigadeiro cremoso e granulado.',
    full_description:
      'Bolo de chocolate molhadinho, camadas generosas de brigadeiro cremoso e granulado macio. Um clássico da matilha para dias que pedem conforto.',
    price: 18,
    promotional_price: null,
    estimated_cost: 7.2,
    stock_quantity: 18,
    image_url: huskyBrand.assets.brigadeiro,
    gallery: [huskyBrand.assets.brigadeiro],
    ingredients_text: 'Chocolate 50%, leite condensado, creme de leite, granulado e bolo de chocolate.',
    size: 'Pote 250 ml',
    is_available: true,
    is_featured: true,
    is_best_seller: true,
    is_limited: false,
    created_at: now,
    updated_at: now,
    likes_count: 248,
    average_rating: 4.9,
  },
  {
    id: 'prod-prestigio',
    name: 'Uivo de Prestígio',
    slug: 'uivo-de-prestigio',
    category: 'Bolos de pote',
    short_description: 'Bolo de chocolate com creme de coco e cobertura cremosa.',
    full_description:
      'Chocolate macio com creme de coco delicado, finalizado com uma cobertura cremosa que deixa o pote equilibrado e marcante.',
    price: 18,
    promotional_price: null,
    estimated_cost: 7.5,
    stock_quantity: 13,
    image_url: huskyBrand.assets.prestigio,
    gallery: [huskyBrand.assets.prestigio],
    ingredients_text: 'Coco ralado, chocolate, leite condensado, creme de leite e bolo de chocolate.',
    size: 'Pote 250 ml',
    is_available: true,
    is_featured: true,
    is_best_seller: false,
    is_limited: false,
    created_at: now,
    updated_at: now,
    likes_count: 173,
    average_rating: 4.8,
  },
  {
    id: 'prod-abana',
    name: 'Abana Rabo',
    slug: 'abana-rabo',
    category: 'Bolos de pote',
    short_description: 'Brigadeiro cremoso com maracujá, equilibrando doçura e acidez.',
    full_description:
      'Um pote vibrante com brigadeiro branco, maracujá e massa leve. Doce na medida, com aquele azedinho que acorda o paladar.',
    price: 18,
    promotional_price: null,
    estimated_cost: 7.1,
    stock_quantity: 9,
    image_url: huskyBrand.assets.maracuja,
    gallery: [huskyBrand.assets.maracuja],
    ingredients_text: 'Maracujá, brigadeiro branco, massa de baunilha e creme de leite.',
    size: 'Pote 250 ml',
    is_available: true,
    is_featured: false,
    is_best_seller: false,
    is_limited: true,
    created_at: now,
    updated_at: now,
    likes_count: 121,
    average_rating: 4.7,
  },
  {
    id: 'prod-pata',
    name: 'Pata Crocante',
    slug: 'pata-crocante',
    category: 'Bolos de pote',
    short_description: 'Bolo de pote com creme, chocolate e Oreo crocante.',
    full_description:
      'Camadas de creme leve, chocolate e Oreo em pedaços para uma mordida crocante e cremosa ao mesmo tempo.',
    price: 18,
    promotional_price: null,
    estimated_cost: 7.8,
    stock_quantity: 0,
    image_url: huskyBrand.assets.mascot,
    gallery: [huskyBrand.assets.mascot],
    ingredients_text: 'Oreo, chocolate, creme branco, leite condensado e massa de chocolate.',
    size: 'Pote 250 ml',
    is_available: false,
    is_featured: true,
    is_best_seller: false,
    is_limited: false,
    created_at: now,
    updated_at: now,
    likes_count: 198,
    average_rating: 4.9,
  },
  {
    id: 'prod-braunie',
    name: 'brAUnie',
    slug: 'braunie',
    category: 'Brownies',
    short_description: 'Brownie intenso e chocolatudo da matilha.',
    full_description:
      'Brownie de casquinha brilhante, centro úmido e sabor profundo de chocolate. Pequeno no tamanho, enorme no uivo.',
    price: 14.9,
    promotional_price: null,
    estimated_cost: 5.4,
    stock_quantity: 24,
    image_url: huskyBrand.assets.post,
    gallery: [huskyBrand.assets.post],
    ingredients_text: 'Chocolate, manteiga, cacau, ovos, farinha e açúcar.',
    size: 'Unidade 90 g',
    is_available: true,
    is_featured: true,
    is_best_seller: true,
    is_limited: false,
    created_at: now,
    updated_at: now,
    likes_count: 316,
    average_rating: 5,
  },
  {
    id: 'prod-combo3',
    name: 'Combo Matilha 3 sabores',
    slug: 'combo-matilha-3-sabores',
    category: 'Combos',
    short_description: 'Escolha 3 bolos de pote para dividir, presentear ou guardar para mais tarde.',
    full_description:
      'Informe os sabores na observação. Se algum acabar, a loja chama no chat e combina a melhor substituição.',
    price: 50,
    promotional_price: 48,
    estimated_cost: 18.5,
    stock_quantity: 8,
    image_url: huskyBrand.assets.combo,
    gallery: [huskyBrand.assets.combo],
    ingredients_text: 'Sabores sortidos conforme disponibilidade.',
    size: '3 potes de 250 ml',
    is_available: true,
    is_featured: true,
    is_best_seller: false,
    is_limited: false,
    created_at: now,
    updated_at: now,
    likes_count: 201,
    average_rating: 4.9,
  },
  {
    id: 'prod-combo4',
    name: 'Combo Família Husky',
    slug: 'combo-familia-husky',
    category: 'Combos',
    short_description: 'Leve 4 bolos de pote com desconto automático no carrinho.',
    full_description: 'Ideal para família, presente coletivo ou para abastecer a geladeira com a matilha inteira.',
    price: 68,
    promotional_price: 64,
    estimated_cost: 24.5,
    stock_quantity: 5,
    image_url: huskyBrand.assets.hero,
    gallery: [huskyBrand.assets.hero],
    ingredients_text: 'Sabores sortidos conforme disponibilidade.',
    size: '4 potes de 250 ml',
    is_available: true,
    is_featured: false,
    is_best_seller: true,
    is_limited: false,
    created_at: now,
    updated_at: now,
    likes_count: 186,
    average_rating: 4.9,
  },
  {
    id: 'prod-presente',
    name: 'Kit Presente Husky',
    slug: 'kit-presente-husky',
    category: 'Combos',
    short_description: 'Dois bolos de pote, sacola kraft e cartão com mensagem.',
    full_description: 'Um presente simples, bonito e pronto para entregar com carinho artesanal.',
    price: 42,
    promotional_price: null,
    estimated_cost: 15,
    stock_quantity: 6,
    image_url: huskyBrand.assets.gift,
    gallery: [huskyBrand.assets.gift],
    ingredients_text: 'Sabores sortidos conforme disponibilidade.',
    size: '2 potes de 250 ml',
    is_available: true,
    is_featured: false,
    is_best_seller: false,
    is_limited: false,
    created_at: now,
    updated_at: now,
    likes_count: 92,
    average_rating: 4.8,
  },
  {
    id: 'prod-cafe',
    name: 'Café gelado da casa',
    slug: 'cafe-gelado-da-casa',
    category: 'Bebidas',
    short_description: 'Café gelado cremoso para acompanhar o bolo de pote.',
    full_description: 'Feito na hora, com calda da casa e aquele toque geladinho para acompanhar a sobremesa.',
    price: 12,
    promotional_price: null,
    estimated_cost: 4,
    stock_quantity: 16,
    image_url: huskyBrand.assets.coffee,
    gallery: [huskyBrand.assets.coffee],
    ingredients_text: 'Café, leite, gelo e calda da casa.',
    size: 'Copo 300 ml',
    is_available: true,
    is_featured: false,
    is_best_seller: false,
    is_limited: true,
    created_at: now,
    updated_at: now,
    likes_count: 52,
    average_rating: 4.7,
  },
];

export const demoCoupons: Coupon[] = [
  {
    id: 'coupon-primeiracolher',
    code: 'PRIMEIRACOLHER',
    description: 'Primeira colher: R$5 de desconto acima de R$30.',
    discount_type: 'fixed',
    discount_value: 5,
    starts_at: new Date(Date.now() - day).toISOString(),
    ends_at: new Date(Date.now() + 60 * day).toISOString(),
    max_uses: 100,
    uses_per_customer: 1,
    minimum_order_value: 30,
    product_id: null,
    category: null,
    is_active: true,
    created_at: now,
    updated_at: now,
  },
  {
    id: 'coupon-husky10',
    code: 'HUSKY10',
    description: '10% de desconto acima de R$50.',
    discount_type: 'percentage',
    discount_value: 10,
    starts_at: new Date(Date.now() - day).toISOString(),
    ends_at: new Date(Date.now() + 45 * day).toISOString(),
    max_uses: 200,
    uses_per_customer: 1,
    minimum_order_value: 50,
    product_id: null,
    category: null,
    is_active: true,
    created_at: now,
    updated_at: now,
  },
  {
    id: 'coupon-fretegratis',
    code: 'FRETEGRATIS',
    description: 'Frete grátis acima de R$50.',
    discount_type: 'free_shipping',
    discount_value: 0,
    starts_at: new Date(Date.now() - day).toISOString(),
    ends_at: new Date(Date.now() + 30 * day).toISOString(),
    max_uses: 120,
    uses_per_customer: 1,
    minimum_order_value: 50,
    product_id: null,
    category: null,
    is_active: true,
    created_at: now,
    updated_at: now,
  },
  {
    id: 'coupon-niverhusky',
    code: 'NIVERHUSKY',
    description: 'R$8 no mês do aniversário.',
    discount_type: 'fixed',
    discount_value: 8,
    starts_at: new Date(Date.now() - day).toISOString(),
    ends_at: new Date(Date.now() + 220 * day).toISOString(),
    max_uses: 80,
    uses_per_customer: 1,
    minimum_order_value: 40,
    product_id: null,
    category: null,
    is_active: true,
    created_at: now,
    updated_at: now,
  },
];

export const demoPolls: Poll[] = [
  {
    id: 'poll-flavor',
    question: 'Qual sabor deve entrar no cardápio?',
    starts_at: new Date(Date.now() - day).toISOString(),
    ends_at: new Date(Date.now() + 12 * day).toISOString(),
    is_active: true,
    created_at: now,
    options: [
      { id: 'poll-opt-1', poll_id: 'poll-flavor', option_text: 'Ninho com Nutella', created_at: now, votes_count: 34 },
      {
        id: 'poll-opt-2',
        poll_id: 'poll-flavor',
        option_text: 'Morango com chocolate',
        created_at: now,
        votes_count: 27,
      },
      { id: 'poll-opt-3', poll_id: 'poll-flavor', option_text: 'Paçoca cremosa', created_at: now, votes_count: 19 },
      {
        id: 'poll-opt-4',
        poll_id: 'poll-flavor',
        option_text: 'Limão com chocolate branco',
        created_at: now,
        votes_count: 21,
      },
    ],
  },
];

export const demoPosts: Post[] = [
  {
    id: 'post-braunie',
    title: 'O brAUnie chegou na matilha!',
    content:
      'Nosso brownie chocolatudo chegou para conquistar seu coração. Crocante por fora, macio por dentro e cheio de personalidade.',
    type: 'Lançamento',
    media_url: huskyBrand.assets.post,
    product_id: 'prod-braunie',
    coupon_id: null,
    poll_id: null,
    status: 'published',
    created_by: null,
    created_at: new Date(Date.now() - 2 * day).toISOString(),
    updated_at: now,
    product: demoProducts[4],
    likes_count: 316,
    comments_count: 42,
  },
  {
    id: 'post-lambe',
    title: 'Lambe Lambe Brigadeiro',
    content:
      'Para quem ama chocolate sem medo. Bolo fofinho, brigadeiro cremoso e aquele granulado que faz a diferença.',
    type: 'Produto',
    media_url: huskyBrand.assets.brigadeiro,
    product_id: 'prod-lambe',
    coupon_id: null,
    poll_id: null,
    status: 'published',
    created_by: null,
    created_at: new Date(Date.now() - 4 * day).toISOString(),
    updated_at: now,
    product: demoProducts[0],
    likes_count: 248,
    comments_count: 31,
  },
  {
    id: 'post-poll',
    title: 'Qual sabor você quer ver por aqui?',
    content: 'A matilha manda! Vote no próximo sabor da Husky.',
    type: 'Enquete',
    media_url: huskyBrand.assets.mascot,
    product_id: null,
    coupon_id: null,
    poll_id: 'poll-flavor',
    status: 'published',
    created_by: null,
    created_at: new Date(Date.now() - 6 * day).toISOString(),
    updated_at: now,
    product: null,
    likes_count: 190,
    comments_count: 28,
  },
];

export const demoStories: Story[] = [
  {
    id: 'story-fornada',
    title: 'Tem fornada hoje!',
    content: 'Brownies saindo do forno e potinhos fresquinhos.',
    media_url: huskyBrand.assets.post,
    button_text: 'Pedir agora',
    button_link: '/app/cardapio',
    product_id: 'prod-braunie',
    coupon_id: null,
    starts_at: new Date(Date.now() - day).toISOString(),
    ends_at: new Date(Date.now() + 2 * day).toISOString(),
    is_active: true,
    created_at: now,
  },
  {
    id: 'story-unidades',
    title: 'Últimas unidades',
    content: 'Pata Crocante está quase sumindo da matilha.',
    media_url: huskyBrand.assets.mascot,
    button_text: 'Ver cardápio',
    button_link: '/app/cardapio',
    product_id: 'prod-pata',
    coupon_id: null,
    starts_at: new Date(Date.now() - day).toISOString(),
    ends_at: new Date(Date.now() + 2 * day).toISOString(),
    is_active: true,
    created_at: now,
  },
  {
    id: 'story-cupom',
    title: 'Cupom liberado',
    content: 'Use HUSKY10 acima de R$50.',
    media_url: huskyBrand.assets.logo,
    button_text: 'Usar cupom',
    button_link: '/app/cupons',
    product_id: null,
    coupon_id: 'coupon-husky10',
    starts_at: new Date(Date.now() - day).toISOString(),
    ends_at: new Date(Date.now() + 2 * day).toISOString(),
    is_active: true,
    created_at: now,
  },
];

export const demoOrders: Order[] = [
  {
    id: 'order-1',
    order_number: 'HC-20260513-001',
    user_id: 'demo-user',
    customer_name: 'Cliente da Matilha',
    customer_phone: huskyBrand.whatsapp,
    delivery_type: 'Entrega',
    address: 'Rua das Flores',
    address_number: '123',
    complement: 'Apto 45',
    neighborhood: 'Centro',
    payment_method: 'PIX',
    subtotal: 50.9,
    discount: 0,
    delivery_fee: huskyBrand.deliveryFee,
    total: 50.9 + huskyBrand.deliveryFee,
    status: 'Confeitando',
    general_observation: 'Caprichar no brigadeiro.',
    coupon_code: null,
    created_at: new Date(Date.now() - 2 * day).toISOString(),
    updated_at: now,
    items: [
      {
        id: 'order-item-1',
        order_id: 'order-1',
        product_id: 'prod-braunie',
        product_name: 'brAUnie',
        quantity: 1,
        unit_price: 14.9,
        subtotal: 14.9,
        observation: null,
        created_at: now,
      },
      {
        id: 'order-item-2',
        order_id: 'order-1',
        product_id: 'prod-lambe',
        product_name: 'Lambe Lambe Brigadeiro',
        quantity: 2,
        unit_price: 18,
        subtotal: 36,
        observation: null,
        created_at: now,
      },
    ],
  },
];

export const demoNotifications: Notification[] = [
  {
    id: 'notif-1',
    user_id: 'demo-user',
    title: 'A Husky está confeitando',
    content: 'Seu pedido HC-20260513-001 entrou em preparo.',
    type: 'order_status',
    is_read: false,
    created_at: now,
  },
  {
    id: 'notif-2',
    user_id: 'demo-user',
    title: 'Patinhas recebidas',
    content: 'Você ganhou 5 patinhas por avaliar a matilha.',
    type: 'points',
    is_read: true,
    created_at: new Date(Date.now() - day).toISOString(),
  },
];

export const demoReviews: Review[] = [
  {
    id: 'review-1',
    order_id: 'order-1',
    product_id: 'prod-lambe',
    user_id: 'demo-user',
    rating: 5,
    comment: 'O Lambe Lambe veio perfeito. O brigadeiro é muito cremoso!',
    can_use_as_feedback: true,
    is_visible: true,
    is_highlighted: true,
    created_at: new Date(Date.now() - 3 * day).toISOString(),
    profile: { name: 'Ana da Matilha', avatar_url: null },
    product: demoProducts[0],
  },
  {
    id: 'review-2',
    order_id: null,
    product_id: 'prod-braunie',
    user_id: 'demo-user',
    rating: 5,
    comment: 'Casquinha brilhante, centro úmido e chocolate de verdade.',
    can_use_as_feedback: true,
    is_visible: true,
    is_highlighted: true,
    created_at: new Date(Date.now() - 5 * day).toISOString(),
    profile: { name: 'Bruno Fiel', avatar_url: null },
    product: demoProducts[4],
  },
];

export const demoInventory: InventoryItem[] = [
  ['Leite condensado', 'Ingredientes', 'un', 18, 8, 6.9],
  ['Creme de leite', 'Ingredientes', 'un', 22, 10, 3.8],
  ['Chocolate em pó 50%', 'Ingredientes', 'kg', 4.5, 2, 32],
  ['Cacau em pó', 'Ingredientes', 'kg', 1.4, 1, 48],
  ['Farinha', 'Ingredientes', 'kg', 8, 3, 5.5],
  ['Açúcar', 'Ingredientes', 'kg', 9, 4, 4.8],
  ['Óleo', 'Ingredientes', 'l', 3, 2, 7.5],
  ['Ovos', 'Ingredientes', 'un', 42, 24, 0.75],
  ['Fermento', 'Ingredientes', 'kg', 0.5, 0.3, 18],
  ['Granulado', 'Ingredientes', 'kg', 2.4, 1, 19],
  ['Coco ralado', 'Ingredientes', 'kg', 1.2, 0.8, 24],
  ['Maracujá', 'Ingredientes', 'kg', 2.2, 1, 12],
  ['Oreo', 'Ingredientes', 'pacote', 8, 5, 4.5],
  ['Manteiga', 'Ingredientes', 'kg', 1.5, 1, 38],
  ['Potes 250 ml', 'Embalagens', 'un', 52, 40, 0.72],
  ['Colheres', 'Embalagens', 'un', 60, 50, 0.18],
  ['Sacolas kraft', 'Embalagens', 'un', 35, 30, 0.65],
  ['Etiquetas', 'Embalagens', 'un', 80, 50, 0.12],
].map(([name, category, unit, current, minimum, cost], index) => ({
  id: `stock-${index + 1}`,
  name: String(name),
  category: String(category),
  unit: String(unit),
  current_quantity: Number(current),
  minimum_quantity: Number(minimum),
  unit_cost: Number(cost),
  supplier: 'Fornecedor Husky',
  last_purchase_date: '2026-05-08',
  created_at: now,
  updated_at: now,
}));

export const demoExpenses: Expense[] = [
  {
    id: 'expense-1',
    description: 'Compra de ingredientes base',
    category: 'Ingredientes',
    amount: 380,
    date: '2026-05-10',
    payment_method: 'PIX',
    receipt_url: null,
    observation: 'Reposição semanal',
    created_at: now,
  },
  {
    id: 'expense-2',
    description: 'Impulsionamento Instagram',
    category: 'Marketing',
    amount: 120,
    date: '2026-05-12',
    payment_method: 'Cartão',
    receipt_url: null,
    observation: 'Campanha brAUnie',
    created_at: now,
  },
];

export const demoLoyaltyHistory: LoyaltyHistory[] = [
  {
    id: 'loyalty-1',
    user_id: 'demo-user',
    points: 56,
    reason: 'Pedido finalizado HC-20260513-001',
    reference_type: 'order',
    reference_id: 'order-1',
    created_at: new Date(Date.now() - 2 * day).toISOString(),
  },
  {
    id: 'loyalty-2',
    user_id: 'demo-user',
    points: 5,
    reason: 'Uivo da Matilha publicado',
    reference_type: 'review',
    reference_id: 'review-1',
    created_at: new Date(Date.now() - 3 * day).toISOString(),
  },
];

export const demoConversations: ChatConversation[] = [
  {
    id: 'chat-demo',
    user_id: 'demo-user',
    status: 'open',
    created_at: now,
    updated_at: now,
    profile: demoProfile,
  },
];

export const demoMessages: ChatMessage[] = [
  {
    id: 'message-1',
    conversation_id: 'chat-demo',
    sender_id: 'demo-admin',
    message: 'Oi! A Husky está por aqui. Como podemos adoçar seu dia? 💙🍰',
    image_url: huskyBrand.assets.mascot,
    is_read: true,
    created_at: new Date(Date.now() - 20 * 60 * 1000).toISOString(),
    sender: demoAdminProfile,
  },
];

export const demoMetrics: DashboardMetrics = {
  salesToday: 482.7,
  pendingOrders: 4,
  monthRevenue: 9820.4,
  estimatedProfit: 3640.2,
  customerCount: 284,
  activeProducts: 8,
  lowStock: 4,
  pendingComments: 3,
  activeCoupons: 4,
  topPostTitle: 'O brAUnie chegou na matilha!',
  salesByDay: [
    { label: 'Seg', value: 320 },
    { label: 'Ter', value: 460 },
    { label: 'Qua', value: 482 },
    { label: 'Qui', value: 390 },
    { label: 'Sex', value: 720 },
    { label: 'Sáb', value: 860 },
    { label: 'Dom', value: 510 },
  ],
  productsSold: [
    { label: 'brAUnie', value: 86 },
    { label: 'Lambe Lambe', value: 74 },
    { label: 'Pata Crocante', value: 52 },
    { label: 'Uivo Prestígio', value: 39 },
  ],
  revenueByMonth: [
    { label: 'Jan', value: 5200 },
    { label: 'Fev', value: 6100 },
    { label: 'Mar', value: 7200 },
    { label: 'Abr', value: 8800 },
    { label: 'Mai', value: 9820 },
  ],
  customersByWeek: [
    { label: 'S1', value: 24 },
    { label: 'S2', value: 31 },
    { label: 'S3', value: 28 },
    { label: 'S4', value: 42 },
  ],
  ordersByStatus: [
    { label: 'Aguardando', value: 4 },
    { label: 'Confeitando', value: 7 },
    { label: 'Entrega', value: 3 },
    { label: 'Finalizado', value: 38 },
  ],
};
