export const huskyBrand = {
  displayName: 'Husky Confeiteiro',
  storeName: 'Husky Confeitaria e Caixa',
  city: 'Embu das Artes',
  state: 'SP',
  whatsapp: '5511945198349',
  instagramHandle: 'huskyconfeiteiro',
  instagramUrl: 'https://www.instagram.com/huskyconfeiteiro/',
  supabaseUrl: 'https://wnhmcbozesilmokyemgh.supabase.co',
  paymentProvider: 'infinitepay',
  infinitePayHandle: 'huskybolos',
  checkoutFunction: 'create-infinitepay-checkout',
  checkFunction: 'check-infinitepay-payment',
  paymentReturnUrl: 'https://husky-app.vercel.app/retorno-pagamento.html',
  deliveryFee: 6.99,
  freeDeliveryFrom: 45,
  minOrder: 18,
  deliveryTime: '35-55 min',
  pickupTime: '20-30 min',
  announcement: 'Forno ligado hoje: pedidos até 21h30.',
  serviceArea: ['Centro', 'Jardim Vista Alegre', 'Parque Pirajussara', 'Santo Eduardo'],
  openingHours: {
    monday: 'Fechado',
    tuesday: '14:00 às 21:00',
    wednesday: '14:00 às 21:00',
    thursday: '14:00 às 21:00',
    friday: '14:00 às 22:00',
    saturday: '12:00 às 22:00',
    sunday: '12:00 às 20:00',
  },
  assets: {
    logo: '/assets/husky/logo.png',
    hero: '/assets/husky/hero.png',
    mascot: '/assets/husky/mascote.png',
    brigadeiro: '/assets/husky/bolo-brigadeiro.png',
    maracuja: '/assets/husky/bolo-maracuja.png',
    prestigio: '/assets/husky/bolo-prestigio.png',
    post: '/assets/husky/post.PNG',
    coffee: '/assets/husky/IMG_7154.JPG.jpeg',
    combo: '/assets/husky/hero.png',
    gift: '/assets/husky/logo.png',
  },
  chatEmojis: ['😍', '😋', '🥳', '💙', '🍰', '✨', '✅', '🚚'],
  chatStickers: [
    { id: 'sticker-01', label: 'Husky 💙', image: '/assets/husky/sticker-01.png' },
    { id: 'sticker-02', label: 'Amei 😍', image: '/assets/husky/sticker-02.png' },
    { id: 'sticker-03', label: 'Delícia 😋', image: '/assets/husky/sticker-03.png' },
    { id: 'sticker-04', label: 'Fornada 🍰', image: '/assets/husky/sticker-04.png' },
    { id: 'sticker-05', label: 'Entrega 🚚', image: '/assets/husky/sticker-05.png' },
    { id: 'brigadeiro', label: 'Brigadeiro', image: '/assets/husky/bolo-brigadeiro.png' },
    { id: 'maracuja', label: 'Abana Rabo', image: '/assets/husky/bolo-maracuja.png' },
    { id: 'prestigio', label: 'Prestígio', image: '/assets/husky/bolo-prestigio.png' },
  ],
  adminEmojis: {
    dashboard: '🏠',
    orders: '🧾',
    kitchen: '👩‍🍳',
    deliveries: '🚚',
    chat: '💬',
    products: '🍰',
    categories: '🗂️',
    addons: '➕',
    inventory: '📦',
    store: '🔓',
    banners: '🖼️',
    customers: '👥',
    coupons: '🎟️',
    reviews: '⭐',
    loyalty: '🏆',
    channels: '📣',
    finance: '💰',
    reports: '📊',
    cash: '💳',
    expenses: '🧾',
    issues: '⚠️',
    manual: '✍️',
    schedule: '📅',
    notifications: '🔔',
    audit: '🕵️',
    users: '🔐',
    settings: '⚙️',
    export: '📤',
  },
};

export const demoStorageVersion = 'husky-social-feed-2026-05-14-v1';
